name: Run .NET Tests with Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Show working directory and structure
        run: |
          echo "Working directory: $(pwd)"
          ls -R

      - name: Clean previous builds
        run: |
          dotnet clean
          find . -type d -name bin -exec rm -rf {} +
          find . -type d -name obj -exec rm -rf {} +

      - name: Restore dependencies
        run: dotnet restore ./TravelEase/src/TravelEase.API/TravelEase.API.csproj

      - name: Build API project
        run: dotnet build ./TravelEase/src/TravelEase.API/TravelEase.API.csproj --no-restore --configuration Release

      - name: Run tests with coverage
        run: |
          dotnet test ./TravelEase/src/TravelEase.Tests/TravelEase.Tests.csproj --no-build --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=cobertura \
            /p:CoverletOutput=./TravelEase/src/TravelEase.Tests/TestResults/

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./TravelEase/src/TravelEase.Tests/TestResults/coverage.cobertura.xml
