name: Run .NET Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Clean build artifacts
        run: |
          dotnet clean
          find . -type d -name bin -exec rm -rf {} +
          find . -type d -name obj -exec rm -rf {} +

      - name: Restore dependencies
        run: dotnet restore ./TravelEase/src/TravelEase.API/TravelEase.API.csproj

      - name: Build project
        run: dotnet build ./TravelEase/src/TravelEase.API/TravelEase.API.csproj --no-restore --configuration Release

      - name: Run unit tests
        run: |
          dotnet test ./TravelEase/src/TravelEase.Tests/TravelEase.Tests.csproj \
            --configuration Release \
            --verbosity normal \
            --logger "trx;LogFileName=test_results.trx"

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/test_results.trx'
